### ISSUE TITLE
UpdateMessage

### ISSUE THREAD

**Issue by eshvatskyi** [richardschneider/net-dns#1]
Do you have plans to support this project?
Will be good to have a possibility to update DNS records

**Comment by richardschneider** [comment]
Yes, I am supporting the project.

This project is a data model for DNS records not a DNS server.  What do you mean by `update DNS records`?


This project is a data model for DNS records not a DNS server.  What do you mean by `update DNS records

**Comment by eshvatskyi** [comment]
https://tools.ietf.org/html/rfc2136

**Comment by richardschneider** [comment]
@eshvatskyi hanks for info, I was not aware of the RFC.  I've added the branch `update-message` and will start to implement it today.

**Comment by eshvatskyi** [comment]
looks cool :) thanks

**Comment by richardschneider** [comment]
Update message is available in release v0.3.0
